"""add microsoft column

Revision ID: 4d78ef4dfd3d
Revises: 865d111dd857
Create Date: 2024-12-08 20:29:32.213852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d78ef4dfd3d'
down_revision: Union[str, None] = '865d111dd857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('microsoft_store_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'microsoft_store_version')
    # ### end Alembic commands ###
