"""create user table

Revision ID: a6b991c79189
Revises: 4d78ef4dfd3d
Create Date: 2024-12-09 06:33:33.048210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b991c79189'
down_revision: Union[str, None] = '4d78ef4dfd3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('play_store_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('app_store_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('force_update', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_pause', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('microsoft_store_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='apps_pkey'),
    sa.UniqueConstraint('package_name', name='apps_package_name_key')
    )
    # ### end Alembic commands ###
